version: '3.9'
services:
  frontend:
    image: frontend
    restart: always
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - server
  server:
    image: server
    restart: always
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - mongo
  mongo:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
    env_file: .env
    volumes:
      - mongo:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports: 8081:8081
    env_file: .env
    depends_on:
      - mongo
volumes:
  mongo:
    driver: local
